#!/usr/bin/env bash
set -euo pipefail

# ============================================
# Nero | Hermes Lifetime Session Runner
# Optimized for GitHub Actions (5h50m + auto restart)
# ============================================

export HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
export PYTHONUNBUFFERED=1
export DASHBOARD_PORT="${DASHBOARD_PORT:-9119}"
export PATH="$HOME/.local/bin:$HOME/.hermes/bin:$PATH"

SESSION_MINUTES=350
LOG_DIR="/tmp/hermes-logs"
mkdir -p "$LOG_DIR" "$HERMES_HOME"

log() { echo "[$(date '+%H:%M:%S')] $*" | tee -a "$LOG_DIR/session.log"; }

install_hermes() {
  if command -v hermes >/dev/null 2>&1; then
    log "Hermes already present: $(hermes --version 2>/dev/null || echo ok)"
    return
  fi
  log "Installing Hermes Agent (official installer)..."
  curl -fsSL https://hermes-agent.nousresearch.com/install.sh | bash
  export PATH="$HOME/.local/bin:$HOME/.hermes/bin:$PATH"
  source "$HOME/.bashrc" 2>/dev/null || true
  if ! command -v hermes >/dev/null 2>&1; then
    log "ERROR: hermes not found after install"
    exit 1
  fi
  log "Hermes installed successfully"
}

# Write .env safely (handles special chars like ! in passwords)
write_env() {
  log "Writing $HERMES_HOME/.env from secrets..."

  # Ensure we always have a stable signing secret (sessions survive restarts)
  if [ -z "${HERMES_DASHBOARD_BASIC_AUTH_SECRET:-}" ] || [ "${HERMES_DASHBOARD_BASIC_AUTH_SECRET}" = "change-me-to-random-32chars-min" ]; then
    HERMES_DASHBOARD_BASIC_AUTH_SECRET="$(openssl rand -base64 48 | tr -d '\n')"
    log "Generated stable HERMES_DASHBOARD_BASIC_AUTH_SECRET"
  fi
  export HERMES_DASHBOARD_BASIC_AUTH_SECRET

  # Default username
  export HERMES_DASHBOARD_BASIC_AUTH_USERNAME="${HERMES_DASHBOARD_BASIC_AUTH_USERNAME:-admin}"
  export HERMES_DASHBOARD_BASIC_AUTH_PASSWORD="${HERMES_DASHBOARD_BASIC_AUTH_PASSWORD:-}"

  # Diagnostics (never print the actual password)
  if [ -n "${HERMES_DASHBOARD_BASIC_AUTH_PASSWORD}" ]; then
    log "Basic Auth: username=${HERMES_DASHBOARD_BASIC_AUTH_USERNAME} password=SET (len=${#HERMES_DASHBOARD_BASIC_AUTH_PASSWORD})"
  else
    log "ERROR: HERMES_DASHBOARD_BASIC_AUTH_PASSWORD is EMPTY — login will fail"
    log "       → Settings → Secrets → Actions → set the secret"
  fi

  # Write file line-by-line to avoid shell expansion issues with special chars
  {
    echo "# Auto-generated by Nero Lifetime Runner - never commit"
    echo "XKIRO_API_KEY=${XKIRO_API_KEY:-}"
    echo "OLLAMA_API_KEY=${OLLAMA_API_KEY:-}"
    echo "GROQ_API_KEY=${GROQ_API_KEY:-}"
    echo "OPENAI_API_KEY=${OPENAI_API_KEY:-}"
    echo "OPENCODE_ZEN_API_KEY=${OPENCODE_ZEN_API_KEY:-}"
    echo "AISUBSCRIPTION_API_KEY=${AISUBSCRIPTION_API_KEY:-}"
    echo "MIAROUTER_API_KEY=${MIAROUTER_API_KEY:-}"
    echo "TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}"
    echo "TELEGRAM_ALLOWED_USERS=${TELEGRAM_ALLOWED_USERS:-}"
    echo "HERMES_DASHBOARD_BASIC_AUTH_USERNAME=${HERMES_DASHBOARD_BASIC_AUTH_USERNAME}"
    echo "HERMES_DASHBOARD_BASIC_AUTH_PASSWORD=${HERMES_DASHBOARD_BASIC_AUTH_PASSWORD}"
    echo "HERMES_DASHBOARD_BASIC_AUTH_SECRET=${HERMES_DASHBOARD_BASIC_AUTH_SECRET}"
    echo "HERMES_HOME=${HERMES_HOME}"
    echo "PYTHONUNBUFFERED=1"
    echo "DASHBOARD_PORT=${DASHBOARD_PORT}"
    echo "OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-https://ollama.com/v1}"
    echo "FIGMA_PAT=${FIGMA_PAT:-}"
    echo "GOOGLE_API_KEY=${GOOGLE_API_KEY:-}"
    echo "GEMINI_API_KEY=${GEMINI_API_KEY:-}"
    echo "GEMINI_BASE_URL=${GEMINI_BASE_URL:-https://generativelanguage.googleapis.com/v1beta/}"
  } > "$HERMES_HOME/.env"

  chmod 600 "$HERMES_HOME/.env"
  log ".env written"
}

write_config() {
  if [ -f "config.yaml" ]; then
    cp -f config.yaml "$HERMES_HOME/config.yaml"
    log "config.yaml installed"
  else
    log "WARN: no config.yaml found in repo"
  fi
}

start_dashboard() {
  local bind_host="${1:-0.0.0.0}"

  pkill -f "hermes dashboard" 2>/dev/null || true
  sleep 1

  log "Starting Hermes Dashboard on ${bind_host}:${DASHBOARD_PORT}..."

  # Force-export auth env so the process definitely sees them
  # (Hermes also reads ~/.hermes/.env, but env wins)
  export HERMES_DASHBOARD_BASIC_AUTH_USERNAME="${HERMES_DASHBOARD_BASIC_AUTH_USERNAME:-admin}"
  export HERMES_DASHBOARD_BASIC_AUTH_PASSWORD="${HERMES_DASHBOARD_BASIC_AUTH_PASSWORD:-}"
  export HERMES_DASHBOARD_BASIC_AUTH_SECRET="${HERMES_DASHBOARD_BASIC_AUTH_SECRET:-}"

  nohup hermes dashboard \
    --host "$bind_host" \
    --port "$DASHBOARD_PORT" \
    --no-open \
    > "$LOG_DIR/dashboard.log" 2>&1 &
  DASH_PID=$!
  log "Dashboard PID=$DASH_PID"

  for i in $(seq 1 50); do
    code=$(curl -s -o /dev/null -w "%{http_code}" "http://127.0.0.1:$DASHBOARD_PORT" || echo "000")
    if echo "$code" | grep -qE '200|401|302|403'; then
      log "Dashboard ready (HTTP $code)"
      # Quick status check
      status=$(curl -s "http://127.0.0.1:$DASHBOARD_PORT/api/status" 2>/dev/null || echo "{}")
      log "Auth status snippet: $(echo "$status" | head -c 300)"
      return 0
    fi
    sleep 1
  done
  log "WARN: Dashboard may not be fully ready yet (last HTTP $code)"
  log "Last dashboard log:"
  tail -30 "$LOG_DIR/dashboard.log" || true
}

start_dashboard_and_tunnel() {
  log "Preparing dashboard extras..."
  if [ -d "$HERMES_HOME/hermes-agent" ]; then
    (
      cd "$HERMES_HOME/hermes-agent"
      if command -v uv >/dev/null 2>&1; then
        uv pip install -e ".[web,pty]" --quiet 2>/dev/null || true
      else
        pip install -e ".[web,pty]" --quiet 2>/dev/null || true
      fi
    )
  fi

  # Bind 0.0.0.0 so Cloudflare Tunnel Host header is accepted.
  start_dashboard "0.0.0.0"

  CLOUDFLARED="/tmp/cloudflared"
  if [ ! -x "$CLOUDFLARED" ]; then
    log "Downloading cloudflared..."
    curl -sL "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64" -o "$CLOUDFLARED"
    chmod +x "$CLOUDFLARED"
  fi

  log "Starting Cloudflare Quick Tunnel..."
  pkill -f cloudflared 2>/dev/null || true
  sleep 1
  nohup "$CLOUDFLARED" tunnel --url "http://127.0.0.1:$DASHBOARD_PORT" \
    > "$LOG_DIR/tunnel.log" 2>&1 &
  TUNNEL_PID=$!
  log "Tunnel PID=$TUNNEL_PID"

  TUNNEL_URL=""
  for i in $(seq 1 40); do
    if [ -f "$LOG_DIR/tunnel.log" ] && grep -q "trycloudflare.com" "$LOG_DIR/tunnel.log"; then
      TUNNEL_URL=$(grep -oE 'https://[a-z0-9-]+\.trycloudflare\.com' "$LOG_DIR/tunnel.log" | head -1 || true)
      if [ -n "$TUNNEL_URL" ]; then
        log ">>> DASHBOARD URL: $TUNNEL_URL"
        echo "$TUNNEL_URL" > /tmp/dashboard-url.txt
        break
      fi
    fi
    sleep 1
  done

  if [ -n "$TUNNEL_URL" ]; then
    TUNNEL_HOST=$(echo "$TUNNEL_URL" | sed -E 's|https?://||' | cut -d/ -f1)
    log "Setting allowed host: $TUNNEL_HOST"

    export HERMES_DASHBOARD_ALLOWED_HOSTS="$TUNNEL_HOST,localhost,127.0.0.1"
    export HERMES_DASHBOARD_PUBLIC_URL="$TUNNEL_URL"

    {
      echo "HERMES_DASHBOARD_ALLOWED_HOSTS=${HERMES_DASHBOARD_ALLOWED_HOSTS}"
      echo "HERMES_DASHBOARD_PUBLIC_URL=${HERMES_DASHBOARD_PUBLIC_URL}"
    } >> "$HERMES_HOME/.env"

    # Restart so allowlist + public URL take effect
    start_dashboard "0.0.0.0"

    if [ -n "${TELEGRAM_BOT_TOKEN:-}" ] && [ -n "${TELEGRAM_ALLOWED_USERS:-}" ]; then
      CHAT_ID=$(echo "$TELEGRAM_ALLOWED_USERS" | cut -d',' -f1 | tr -d ' ')
      curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
        --data-urlencode "chat_id=${CHAT_ID}" \
        --data-urlencode "text=🚀 Hermes Lifetime is LIVE

Dashboard:
${TUNNEL_URL}

Login: admin / (password di secrets)
Session ~5h50m
_Nero Power_" \
        -d "parse_mode=Markdown" >/dev/null 2>&1 || true
      log "Telegram notification sent to $CHAT_ID"
    fi
  else
    log "WARN: Could not extract tunnel URL"
  fi
}

start_gateway() {
  log "Starting Hermes Gateway..."
  pkill -f "hermes gateway" 2>/dev/null || true
  sleep 1
  nohup hermes gateway > "$LOG_DIR/gateway.log" 2>&1 &
  GATEWAY_PID=$!
  log "Gateway PID=$GATEWAY_PID"
  sleep 6
  if ! kill -0 $GATEWAY_PID 2>/dev/null; then
    log "ERROR: Gateway failed. Last log:"
    tail -80 "$LOG_DIR/gateway.log" || true
    exit 1
  fi
  log "Gateway is running"
}

main() {
  log "=== Nero Hermes Lifetime Session START ==="
  log "Runner: $(uname -a)"
  log "Free RAM: $(free -h | awk '/Mem:/{print $7}')"

  install_hermes
  write_env
  write_config

  start_dashboard_and_tunnel
  start_gateway

  END_TIME=$(( $(date +%s) + SESSION_MINUTES * 60 ))
  log "Session will end around $(date -d "@$END_TIME" 2>/dev/null || date) (${SESSION_MINUTES} minutes)"

  while [ $(date +%s) -lt $END_TIME ]; do
    if ! kill -0 ${GATEWAY_PID:-0} 2>/dev/null; then
      log "Gateway died — restarting..."
      start_gateway
    fi
    if ! kill -0 ${DASH_PID:-0} 2>/dev/null; then
      log "Dashboard/tunnel died — restarting..."
      start_dashboard_and_tunnel
    fi
    sleep 60
  done

  log "Session time reached. Cleaning up and exiting so next job can start..."
  pkill -f "hermes gateway" 2>/dev/null || true
  pkill -f "hermes dashboard" 2>/dev/null || true
  pkill -f cloudflared 2>/dev/null || true
  log "=== Session END ==="
}

main
